In [5]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from sklearn.metrics import roc_auc_score, roc_curve

import matplotlib.pyplot as plt
# import seaborn as sns
#import plotly.express as px

import warnings
warnings.filterwarnings("ignore")
import seaborn as sns

ModuleNotFoundError: No module named 'seaborn'

In [6]:
pip install seaborn

     ------------------------------------ 288.2/288.2 kB 741.3 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [ ]:
#Data Gathering
df = pd.read_csv("Fish.csv", delimiter = "\t")
df

In [ ]:
# EDA 
df.info()

In [ ]:
df.describe()

In [ ]:
df.isna().sum()

In [ ]:
x = df.drop("Species",axis = 1)
y = df["Species"]

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25, random_state = 18, stratify = y)
x_train

In [ ]:
y_test.info()

In [26]:
y_train.value_counts()

Perch        42
Bream        26
Roach        15
Pike         13
Smelt        10
Parkki        8
Whitefish     5
Name: Species, dtype: int64

In [27]:
y_test.value_counts()

Perch        14
Bream         9
Roach         5
Pike          4
Smelt         4
Parkki        3
Whitefish     1
Name: Species, dtype: int64

In [28]:
# Model Training
model = LogisticRegression(multi_class = "ovr")
model.fit(x_train,y_train)

LogisticRegression(multi_class='ovr')

In [29]:
# Evaluation 
def metrics(a,b):
    cnf_matrix = confusion_matrix(a,b)
    print("The Confusion Matrix is :\n", cnf_matrix)
    print("*"*40)
    accuracy = accuracy_score(a,b)
    print("Accuracy is :",accuracy)
    print("*"*40)

    clf_report = classification_report(a,b)
    print("Classification Report :\n",clf_report)
    print("*"*40)


    

In [30]:
# Evaluation for Testing Data 
y_pred = model.predict(x_test)
metrics(y_test,y_pred)

The Confusion Matrix is :
 [[ 9  0  0  0  0  0  0]
 [ 1  2  0  0  0  0  0]
 [ 0  0 14  0  0  0  0]
 [ 0  0  0  4  0  0  0]
 [ 0  0  0  0  4  1  0]
 [ 0  0  0  0  0  4  0]
 [ 0  0  0  0  1  0  0]]
****************************************
Accuracy is : 0.925
****************************************
Classification Report :
               precision    recall  f1-score   support

       Bream       0.90      1.00      0.95         9
      Parkki       1.00      0.67      0.80         3
       Perch       1.00      1.00      1.00        14
        Pike       1.00      1.00      1.00         4
       Roach       0.80      0.80      0.80         5
       Smelt       0.80      1.00      0.89         4
   Whitefish       0.00      0.00      0.00         1

    accuracy                           0.93        40
   macro avg       0.79      0.78      0.78        40
weighted avg       0.91      0.93      0.91        40

****************************************


In [31]:
# Evaluation on training data
y_pred_train = model.predict(x_train)
metrics(y_train,y_pred_train)

The Confusion Matrix is :
 [[26  0  0  0  0  0  0]
 [ 0  8  0  0  0  0  0]
 [ 0  0 42  0  0  0  0]
 [ 0  0  0 13  0  0  0]
 [ 0  0  1  0 14  0  0]
 [ 0  0  0  0  0 10  0]
 [ 0  0  5  0  0  0  0]]
****************************************
Accuracy is : 0.9495798319327731
****************************************
Classification Report :
               precision    recall  f1-score   support

       Bream       1.00      1.00      1.00        26
      Parkki       1.00      1.00      1.00         8
       Perch       0.88      1.00      0.93        42
        Pike       1.00      1.00      1.00        13
       Roach       1.00      0.93      0.97        15
       Smelt       1.00      1.00      1.00        10
   Whitefish       0.00      0.00      0.00         5

    accuracy                           0.95       119
   macro avg       0.84      0.85      0.84       119
weighted avg       0.91      0.95      0.93       119

****************************************


In [32]:
x_train.head(1).T

74
Weight   40.000
Length1  13.800
Length2  15.000
Length3  16.000
Height    3.824
Width     2.432

In [33]:
Weight=45
Length1=19
Length2=16.000
Length3=17.000
Height=7
Width=5

test_array = np.array([Weight,Length1,Length2,Length3,Height,Width], ndmin = 2)
pred_class = model.predict(test_array)[0]
pred_class

'Perch'

In [34]:
import pickle

with open("Fish_species_detection.pkl","wb") as f:
    pickle.dump(model,f)

In [1]:
import config
import pickle
import numpy as np
import pandas as pd
import json

class FishSpecies:
    def __init__(self, user_data):
        self.model_file_path = "Fish_species_detection.pkl"
        self.user_data = user_data
    
    def load_saved_data(self):
        with open ("Fish_species_detection.pkl", "rb") as f:
            self.model = pickle.load(f)

    def get_prediction(self):
        self.load_saved_data()

        Weight= eval(self.user_data["Weight"])

        Length1=eval(self.user_data["Length1"])
        Length2=eval(self.user_data["Length2"])
        Length3=eval(self.user_data["Length3"])
        Height=eval(self.user_data["Height"])
        Width=eval(self.user_data["Width"])
        test_array = np.array([Weight,Length1,Length2,Length3,Height,Width], ndmin = 2)
        predicted_class = self.model.predict(test_array)[0]
        return predicted_class

if __name__ =="__main__":
    fish = FishSpecies()

TypeError: FishSpecies.__init__() missing 1 required positional argument: 'user_data'

In [6]:
user_data = data : ImmutableMultiDict([("Weight":"45"),
("Length1":"19"),
("Length2":"16.000"),
("Length3":"17.000"),
("Height":"7"),
("Width":"5")])

SyntaxError: invalid syntax (2524892075.py, line 1)

In [3]:
from flask import Flask, jsonify, render_template, request, redirect
import config
from utils import FishSpecies

app = Flask(__name__)
# @app.route('/')
# def man():
#     return render_template('home.html')


@app.route('/predict',methods = ['GET', "POST"])

def predict():
    if request.method == 'POST':
        data = request.form
        
        print('data :',data)

        species_fish = FishSpecies(data)
        pred_class = species_fish.get_prediction()
        print("::::::::::",pred_class)
        
        
        return jsonify({"Fish Species": "pred_class"})
    # return render_template('after.html', data=pred_class)
        # if pred_class == 1:

    #     else:
    #         return jsonify({"Outcome": "Person has no Diabetes"})
    #    return f"{pred_class}"
    #     return jsonify({"class" :0 })
